name: "CI setup"

inputs:
  token:
    description: 'Github Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: Use Node.js 21
      uses: actions/setup-node@v4
      with:
        registry-url: "https://npm.pkg.github.com"
        node-version: 21
        cache: "pnpm"

    - name: Set Github Token
      run: |
        rm -f ./.npmrc
        echo "@restx98:registry=https://npm.pkg.github.com" > .npmrc
        echo "//npm.pkg.github.com/:_authToken=${TOKEN}" > .npmrc
        echo "_auth=${TOKEN}" >> .npmrc
        echo "always-auth=true" >> .npmrc
      env:
        TOKEN: ${{inputs.token}}
      shell: bash

    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile
      shell: bash
