name: CI

on:
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  linting:
    name: 🕵 Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/ci-setup
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Linting
        run: pnpm lint

  format:
    name: 💅 Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/ci-setup
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Formatting
        run: pnpm format:check

  build:
    name: 💣 Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/ci-setup
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Building
        run: pnpm build
