name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    permissions:
      contents: write # to create release
      pull-requests: write # to create pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/ci-setup
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
